# Site setting
title: Hidrokit Notebook
description: Kumpulan jupyter notebook hidrologi

# Remote Setting
baseurl: "/hidrokit-nb"
# url: "http://taruma.github.com"

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Enable or disable the site search
# Use this command to update index: bundle exec just-the-docs rake search:init
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View in GitHub":
    - "//github.com/taruma/hidrokit-nb"
